/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistascentral.almacen;

import proyectobd2.vista.vistassucursal.vistasalmacen.*;
import java.io.IOException;
import proyectobd2.modelo.DAO.BitacoraPedidosDAO;
import proyectobd2.modelo.ExportarExcel;

/**
 *
 * @author endri
 */
public class GUIItemsStockMinimo extends javax.swing.JPanel {

    
    private int idSucursal;

    /**
     * Creates new form GUIItemsStockMinimo
     */
    public GUIItemsStockMinimo(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        BitacoraPedidosDAO.obtenerItemsStockMinimo(tb_stockMinimo, idSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_stockMinimo = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel8 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_exelMinimo = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tb_stockMinimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARTICULO", "STOCK ACTUAL", "STOCK MÍNIMO", "DIFERENCIA"
            }
        ));
        jScrollPane1.setViewportView(tb_stockMinimo);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel10.add(filler4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Articulos con stock mínimo");
        jPanel10.add(jLabel8);
        jPanel10.add(filler5);

        btn_exelMinimo.setText("Exportar a Exel");
        btn_exelMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exelMinimoActionPerformed(evt);
            }
        });
        jPanel10.add(btn_exelMinimo);

        add(jPanel10, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exelMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exelMinimoActionPerformed

        ExportarExcel obj;
        try {
            obj = new ExportarExcel();
            obj.exportarExcel(tb_stockMinimo);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_exelMinimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exelMinimo;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_stockMinimo;
    // End of variables declaration//GEN-END:variables
}
