/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistaskardex;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import proyectobd2.modelo.DAO.ItemDAO;
import proyectobd2.modelo.DAO.KardexDAO;
import proyectobd2.modelo.beans.Item;
import proyectobd2.modelo.beans.Kardex;

/**
 *
 * @author basa2
 */
public class GUIKardex extends javax.swing.JPanel {
    int idSucursal;
    String rol;
    int idItem;
    ItemDAO itemDAO = new ItemDAO();
    /**
     * Creates new form GUIKardex
     */
    public GUIKardex(int idSucursal, String rol) {
        initComponents();
        this.idSucursal = idSucursal;
        this.rol = rol;
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbxArticulo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKardex = new javax.swing.JTable();

        jLabel3.setText("jLabel3");

        setMinimumSize(new java.awt.Dimension(1000, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Kárdex");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel2.setText("Consulte el histórico de precios y costo promedio por artículo  ");
        jPanel1.add(jLabel2);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setMaximumSize(new java.awt.Dimension(2000, 38));
        jPanel3.setMinimumSize(new java.awt.Dimension(805, 38));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setText("Seleccione un artículo");
        jPanel3.add(jLabel4);

        cbxArticulo.setAlignmentX(0.0F);
        cbxArticulo.addActionListener(this::cbxArticuloActionPerformed);
        jPanel3.add(cbxArticulo);

        jPanel1.add(jPanel3);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        jLabel5.setText("Histórico de precios");
        jPanel4.add(jLabel5, java.awt.BorderLayout.NORTH);

        tblKardex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Fecha", "Precio de compra", "Precio promedio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblKardex);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxArticuloActionPerformed
        KardexDAO kardexDao = new KardexDAO();
        try {
            Item itemSeleccionado = (Item) cbxArticulo.getSelectedItem();
            if (itemSeleccionado != null) {
                int idItemEspecifico = itemSeleccionado.getIdItem();
                List<Kardex> lista = kardexDao.obtenerKardexEspecifico(idItemEspecifico);
                DefaultTableModel modelo = new DefaultTableModel();
                modelo.addColumn("Folio");
                modelo.addColumn("Fecha");
                modelo.addColumn("Precio de compra");
                modelo.addColumn("Precio promedio");
                for (Kardex kardex : lista) {
                    Object[] fila = new Object[4]; 

                    fila[0] = kardex.getFolio();
                    fila[1] = kardex.getFecha();
                    fila[2] = kardex.getCosto();
                    fila[3] = kardex.getCostoPromedio();
                    modelo.addRow(fila);
                }
                tblKardex.setModel(modelo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + ex.getMessage());
        }
    }//GEN-LAST:event_cbxArticuloActionPerformed

    private void llenarCombo(){
        try{
            List<Item> listaItems = new ArrayList<>();
            if ("Usuario central".equals(rol)) {
                listaItems = itemDAO.obtenerListaObjetos();
            } 
            if ("Usuario sucursal".equals(rol) || "Usuario salidas".equals(rol)) {
                listaItems = itemDAO.obtenerListaPorSucursal(idSucursal);
            }
            DefaultComboBoxModel<Item> modeloCombo = new DefaultComboBoxModel<>();
            for (Item item : listaItems) {
                    modeloCombo.addElement(item);
            }
            cbxArticulo.setModel(modeloCombo);
        } catch (SQLException e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Item> cbxArticulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKardex;
    // End of variables declaration//GEN-END:variables
}
