/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistasdepartamento;

import java.awt.Dialog;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectobd2.modelo.DAO.DetalleSalidaDAO;
import proyectobd2.modelo.DAO.PeticionSalidaDAO;
import proyectobd2.modelo.beans.Departamento;
import proyectobd2.modelo.beans.DetalleSalida;
import proyectobd2.modelo.beans.Item;
import proyectobd2.modelo.beans.PeticionSalida;
import java.sql.SQLException;
import java.util.List;
import proyectobd2.modelo.DAO.ItemDAO;
import proyectobd2.vista.vistassucursal.vistasentradas.GUISeleccionarItem;

/**
 *
 * @author endri
 */
public class GUINuevaSalidaDepartamento extends javax.swing.JPanel {

    private int idSucursal;
    private Item itemSeleccionado;
    private List<Departamento> departamentosSucursal;

    /**
     * Creates new form GUINuevaSalida
     */
    public GUINuevaSalidaDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_departamentoSolicitante = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_guardar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        spn_cantidad = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_articulos = new javax.swing.JTable();
        btn_agregarArticulo = new javax.swing.JButton();
        spn_fecha = new javax.swing.JSpinner();
        lb_nombreItem = new javax.swing.JLabel();
        btn_buscarItem = new javax.swing.JButton();
        lb_personaEncargada = new javax.swing.JLabel();
        txt_usoMaterial = new javax.swing.JTextField();
        lbl_usoMaterial = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Información de la solicitud");

        jLabel2.setText("Fecha:");

        jLabel4.setText("Persona encargada:");

        cb_departamentoSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Materiales solicitados");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Artículo");

        btn_guardar.setBackground(new java.awt.Color(0, 204, 0));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        jLabel5.setText("Departamento solicitante:");

        tb_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_articulos);

        btn_agregarArticulo.setBackground(new java.awt.Color(0, 204, 0));
        btn_agregarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_agregarArticulo.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregarArticulo.setText("Agregar artículo");
        btn_agregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarArticuloActionPerformed(evt);
            }
        });

        spn_fecha.setModel(new javax.swing.SpinnerDateModel());
        spn_fecha.setEditor(new javax.swing.JSpinner.DateEditor(spn_fecha, "dd/MM/yyyy"));

        lb_nombreItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscarItem.setText("Buscar item");
        btn_buscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarItemActionPerformed(evt);
            }
        });

        txt_usoMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usoMaterialActionPerformed(evt);
            }
        });

        lbl_usoMaterial.setText("Uso del material:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btn_buscarItem)
                                                .addGap(67, 67, 67)
                                                .addComponent(lb_nombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel8)
                                            .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(cb_departamentoSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(lb_personaEncargada, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(btn_guardar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_usoMaterial)
                                    .addComponent(txt_usoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_agregarArticulo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(476, 476, 476))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lbl_usoMaterial)
                        .addGap(4, 4, 4)
                        .addComponent(txt_usoMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_personaEncargada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_departamentoSolicitante))
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscarItem)
                            .addComponent(lb_nombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardar)
                    .addComponent(btn_agregarArticulo)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tb_articulos.getModel();
        if (modelo.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Debe agregar al menos un artículo a la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int index = cb_departamentoSolicitante.getSelectedIndex();
        if (index < 0 || index >= departamentosSucursal.size()) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un departamento.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Departamento deptoSeleccionado = departamentosSucursal.get(index);

        PeticionSalida peticion = new PeticionSalida();
        try {
            Date fechaSeleccionada = (Date) spn_fecha.getValue();
            peticion.setFecha(fechaSeleccionada);
        } catch (ClassCastException ex) {
            JOptionPane.showMessageDialog(this, "Fecha inválida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        peticion.setIdEmpleadoAlmacen(deptoSeleccionado.getIdEncargado());
        peticion.setIdEstadoPeticion(2);

        int idPeticionGenerado = PeticionSalidaDAO.insertar(peticion);

        if (idPeticionGenerado > 0) {
            boolean errorEnDetalles = false;

            for (int i = 0; i < modelo.getRowCount(); i++) {
                String nombreArticulo = modelo.getValueAt(i, 0).toString();
                int cantidadArticulo = Integer.parseInt(modelo.getValueAt(i, 1).toString());

                try {
                    Item itemActual = ItemDAO.buscarPorNombre(nombreArticulo, this.idSucursal);
                    if (itemActual != null) {
                        DetalleSalida detalle = new DetalleSalida();
                        detalle.setIdItem(itemActual.getIdItem());
                        detalle.setIdPeticionSalida(idPeticionGenerado);
                        detalle.setCantidad(cantidadArticulo);

                        DetalleSalidaDAO.insertar(detalle);
                    }
                } catch (SQLException e) {
                    errorEnDetalles = true;
                    e.printStackTrace();
                }
            }

            if (errorEnDetalles) {
                JOptionPane.showMessageDialog(this, "La petición se creó, pero hubo un error guardando algunos detalles.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Petición de salida guardada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }


        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar la petición.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_agregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarArticuloActionPerformed
        if (itemSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un artículo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int cantidad = (int) spn_cantidad.getValue();
        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a 0.", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (cantidad > itemSeleccionado.getExistencias()) {
            JOptionPane.showMessageDialog(this, "El máximo de existencias de este ítem son: " + itemSeleccionado.getExistencias(), "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tb_articulos.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (modelo.getValueAt(i, 0).equals(itemSeleccionado.getNombreItem())) {
                JOptionPane.showMessageDialog(this, "El artículo ya está en la lista.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        Object[] fila = new Object[2];
        fila[0] = itemSeleccionado.getNombreItem();
        fila[1] = cantidad;

        modelo.addRow(fila);

        itemSeleccionado = null;
        lb_nombreItem.setText("");
        spn_cantidad.setValue(0);
    }//GEN-LAST:event_btn_agregarArticuloActionPerformed

    private void btn_buscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarItemActionPerformed
        GUISeleccionarItem seleccionarItem = new GUISeleccionarItem((Dialog) this.getParent(), true, this.idSucursal);
        seleccionarItem.setVisible(true);
        String seleccionado = seleccionarItem.getItemSeleccionado();
        if (seleccionado != null) {
            try {
                this.itemSeleccionado = ItemDAO.buscarPorNombre(seleccionado, this.idSucursal);
                if (this.itemSeleccionado != null) {
                    lb_nombreItem.setText(this.itemSeleccionado.getNombreItem());
                    txt_usoMaterial.setText(itemSeleccionado.getDescripcionUso());
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_buscarItemActionPerformed

    private void txt_usoMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usoMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usoMaterialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarArticulo;
    private javax.swing.JButton btn_buscarItem;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cb_departamentoSolicitante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_nombreItem;
    private javax.swing.JLabel lb_personaEncargada;
    private javax.swing.JLabel lbl_usoMaterial;
    private javax.swing.JSpinner spn_cantidad;
    private javax.swing.JSpinner spn_fecha;
    private javax.swing.JTable tb_articulos;
    private javax.swing.JTextField txt_usoMaterial;
    // End of variables declaration//GEN-END:variables
}
