/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectobd2.vista;

import proyectobd2.modelo.DAO.FacturaDAO;
import proyectobd2.modelo.beans.Factura;

/**
 *
 * @author endri
 */
public class GUIArticulosFactura extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIArticulosFactura.class.getName());

    /**
     * Creates new form GUIArticulosFactura
     */
    public GUIArticulosFactura(java.awt.Frame parent, boolean modal, String fac) {
        super(parent, modal);
        initComponents();
        FacturaDAO fDAO = new FacturaDAO();
        fDAO.obtenerArticulosFolio(tb_articulosFolio, fac);
        this.pack();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_folio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_articulosFolio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 333));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Folio:");
        jPanel2.add(jLabel2);

        lb_folio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_folio.setText("*");
        jPanel2.add(lb_folio);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tb_articulosFolio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARTICULO", "CANTIDAD", "FOLIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_articulosFolio);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_folio;
    private javax.swing.JTable tb_articulosFolio;
    // End of variables declaration//GEN-END:variables
}
