/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista;

import proyectobd2.modelo.DAO.BitacoraOperacionesBajaDAO;

/**
 *
 * @author endri
 */
public class GUIBajasRegistradas extends javax.swing.JPanel {

    BitacoraOperacionesBajaDAO bobDAO = new BitacoraOperacionesBajaDAO();
    /**
     * Creates new form GUIBajasRegistradas
     */
    public GUIBajasRegistradas(int idSucursal) {
        initComponents();
        bobDAO.obtenerBajasRegistradas(tb_bajas, idSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tb_bajas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_bajaItem = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        tb_bajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "ARTÍCULO", "RAZÓN", "CANTIDAD SOBRANTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tb_bajas);

        add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel3.add(filler6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bitacora de operaciones");
        jPanel3.add(jLabel1);
        jPanel3.add(filler1);

        btn_bajaItem.setText("Realizar baja");
        jPanel3.add(btn_bajaItem);

        add(jPanel3, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bajaItem;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tb_bajas;
    // End of variables declaration//GEN-END:variables
}
