/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import proyectobd2.modelo.DAO.FacturaDAO;
import proyectobd2.modelo.beans.Factura;

/**
 *
 * @author endri
 */
public class GUIEntradas extends javax.swing.JPanel {

    FacturaDAO fDAO = new FacturaDAO();
    Factura fac = new Factura();
    private int idSucursal;

    /**
     * Creates new form Dashboard
     */
    public GUIEntradas(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        fDAO.obtenerEntradas(tb_entradas, this.idSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_folio = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevaEntrada = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_entradas = new javax.swing.JTable();

        jTextField1.setText("jTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Buscar por folio de factura:");
        jPanel1.add(jLabel1);

        txt_folio.setMinimumSize(new java.awt.Dimension(150, 22));
        txt_folio.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txt_folio);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);

        btn_nuevaEntrada.setText("Nueva entrada");
        btn_nuevaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevaEntrada);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tb_entradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FOLIO", "FECHA", "PROVEEDOR", "RFC", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_entradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_entradasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_entradas);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevaEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nuevaEntradaActionPerformed

    private void tb_entradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_entradasMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tb_entradas.getSelectedRow();

            if (fila != -1) {
                String folio = tb_entradas.getValueAt(fila, 0).toString();
//                try {
//                    //fac = fDAO.buscar(folio);
//                    
//                } catch (SQLException ex) {
//                    
//
//                }
                JFrame framePadre = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);

                GUIArticulosFactura articulosFactura = new GUIArticulosFactura(framePadre, true, folio);
                articulosFactura.setVisible(true);

            }
        }
    }//GEN-LAST:event_tb_entradasMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String folio = txt_folio.getText();
        if (!folio.isEmpty()) {
            try {
                fDAO.buscar(folio, idSucursal, tb_entradas);
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        }else{
            fDAO.obtenerEntradas(tb_entradas, this.idSucursal);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_nuevaEntrada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tb_entradas;
    private javax.swing.JTextField txt_folio;
    // End of variables declaration//GEN-END:variables
}
