/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista;

/**
 *
 * @author endri
 */
public class GUIInventario extends javax.swing.JPanel {

    /**
     * Creates new form GUIInventario
     */
    public GUIInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_stockMinimo = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel8 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_exelMinimo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_exelMaximo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_stockMaximo = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_bajas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_bajaItem = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(452, 435));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        tb_stockMinimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARTICULO", "STOCK ACTUAL", "STOCK MÍNIMO", "DIFERENCIA"
            }
        ));
        jScrollPane1.setViewportView(tb_stockMinimo);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel10.add(filler4);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Articulos con stock mínimo");
        jPanel10.add(jLabel8);
        jPanel10.add(filler5);

        btn_exelMinimo.setText("Exportar a Exel");
        jPanel10.add(btn_exelMinimo);

        jPanel1.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Bitácora pedidos", jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel4.add(filler3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Articulos con stock alto");
        jPanel4.add(jLabel2);
        jPanel4.add(filler2);

        btn_exelMaximo.setText("Exportar a excel");
        jPanel4.add(btn_exelMaximo);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tb_stockMaximo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARTICULO", "ATOCK ACTUAL", "STOCK MÁXIMO", "DIFERENCIA"
            }
        ));
        jScrollPane2.setViewportView(tb_stockMaximo);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Alertas de stock máximo", jPanel2);

        jPanel5.setLayout(new java.awt.BorderLayout());

        tb_bajas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "ARTÍCULO", "RAZÓN", "CANTIDAD RESTANTE ", "USUARIO"
            }
        ));
        jScrollPane4.setViewportView(tb_bajas);

        jPanel5.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel3.add(filler6);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Bitacora de operaciones");
        jPanel3.add(jLabel1);
        jPanel3.add(filler1);

        btn_bajaItem.setText("Realizar baja");
        jPanel3.add(btn_bajaItem);

        jPanel5.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Bajas registradas", jPanel5);

        add(jTabbedPane1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bajaItem;
    private javax.swing.JButton btn_exelMaximo;
    private javax.swing.JButton btn_exelMinimo;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tb_bajas;
    private javax.swing.JTable tb_stockMaximo;
    private javax.swing.JTable tb_stockMinimo;
    // End of variables declaration//GEN-END:variables
}
