package proyectobd2.vista;

import java.awt.CardLayout;
import proyectobd2.modelo.beans.Empleado;

/**
 *
 * @author basa2
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private CardLayout card = null;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(Empleado empleado) {
        initComponents();
        card = (CardLayout) pnl_cuerpo.getLayout();
        int idSucursal = empleado.getIdSucursal();
        GUIEntradas panelEntradas = new GUIEntradas(idSucursal);
        GUISalidas panelSalidas = new GUISalidas(idSucursal);
        GUIItemsStockMinimo panelItemsMinimo = new GUIItemsStockMinimo(idSucursal);
        GUIItemsStockMaximo panelItemsMaximo = new GUIItemsStockMaximo(idSucursal);
        GUIBajasRegistradas panelBajasRegistradas = new GUIBajasRegistradas(idSucursal);

        pnl_cuerpo.add(panelItemsMinimo, "itemsStockMinimo");
        pnl_cuerpo.add(panelItemsMaximo, "itemsStockMaximo");
        pnl_cuerpo.add(panelBajasRegistradas, "bajasRegistradas");
        pnl_cuerpo.add(panelEntradas, "entradas");
        pnl_cuerpo.add(panelSalidas, "salidas");

        pnl_cuerpo.add(new GUIReportes(), "CARD_REPORTES");
        pnl_cuerpo.add(new GUIKardex(), "CARD_KARDEX");
        pnl_cuerpo.add(new GUICatalogo(), "CARD_CATALOGOS");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cuerpo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mb_File = new javax.swing.JMenu();
        mi_cerrarSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_entradas = new javax.swing.JMenuItem();
        mi_salidas = new javax.swing.JMenuItem();
        m_almacen = new javax.swing.JMenu();
        mi_stockMinimo = new javax.swing.JMenuItem();
        mi_stockMaximo = new javax.swing.JMenuItem();
        mi_bajasRegistradas = new javax.swing.JMenuItem();
        mi_kardex = new javax.swing.JMenuItem();
        mi_reportes = new javax.swing.JMenuItem();
        mi_catalogos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(977, 550));

        pnl_cuerpo.setMinimumSize(new java.awt.Dimension(825, 550));
        pnl_cuerpo.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnl_cuerpo.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnl_cuerpo, java.awt.BorderLayout.CENTER);

        mb_File.setText("Archivo");

        mi_cerrarSesion.setText("Cerrar sesión");
        mi_cerrarSesion.addActionListener(this::mi_cerrarSesionActionPerformed);
        mb_File.add(mi_cerrarSesion);

        jMenuBar1.add(mb_File);

        jMenu2.setText("Categorías");

        mi_entradas.setText("Entradas");
        mi_entradas.addActionListener(this::mi_entradasActionPerformed);
        jMenu2.add(mi_entradas);

        mi_salidas.setText("Salidas");
        mi_salidas.addActionListener(this::mi_salidasActionPerformed);
        jMenu2.add(mi_salidas);

        m_almacen.setText("Almacén");

        mi_stockMinimo.setText("Items con stock mínimo");
        mi_stockMinimo.addActionListener(this::mi_stockMinimoActionPerformed);
        m_almacen.add(mi_stockMinimo);

        mi_stockMaximo.setText("Items con stock máximo");
        mi_stockMaximo.addActionListener(this::mi_stockMaximoActionPerformed);
        m_almacen.add(mi_stockMaximo);

        mi_bajasRegistradas.setText("Bajas registradas");
        mi_bajasRegistradas.addActionListener(this::mi_bajasRegistradasActionPerformed);
        m_almacen.add(mi_bajasRegistradas);

        jMenu2.add(m_almacen);

        mi_kardex.setText("Kardex");
        mi_kardex.addActionListener(this::mi_kardexActionPerformed);
        jMenu2.add(mi_kardex);

        mi_reportes.setText("Reportes");
        mi_reportes.addActionListener(this::mi_reportesActionPerformed);
        jMenu2.add(mi_reportes);

        mi_catalogos.setText("Catálogos");
        mi_catalogos.addActionListener(this::mi_catalogosActionPerformed);
        jMenu2.add(mi_catalogos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_entradasActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        // Le pedimos que muestre el panel con el nombre que definimos antes
        card.show(pnl_cuerpo, "entradas");
    }//GEN-LAST:event_mi_entradasActionPerformed

    private void mi_salidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salidasActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();

        card.show(pnl_cuerpo, "salidas");
    }//GEN-LAST:event_mi_salidasActionPerformed

    private void mi_kardexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_kardexActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "CARD_kARDEX");
    }//GEN-LAST:event_mi_kardexActionPerformed

    private void mi_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_reportesActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "CARD_REPORTES");
    }//GEN-LAST:event_mi_reportesActionPerformed

    private void mi_catalogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_catalogosActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "CARD_CATALOGO");
    }//GEN-LAST:event_mi_catalogosActionPerformed

    private void mi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_mi_cerrarSesionActionPerformed

    private void mi_stockMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_stockMinimoActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "itemsStockMinimo");
    }//GEN-LAST:event_mi_stockMinimoActionPerformed

    private void mi_stockMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_stockMaximoActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "itemsStockMaximo");
    }//GEN-LAST:event_mi_stockMaximoActionPerformed

    private void mi_bajasRegistradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_bajasRegistradasActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();
        card.show(pnl_cuerpo, "bajasRegistradas");
    }//GEN-LAST:event_mi_bajasRegistradasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu m_almacen;
    private javax.swing.JMenu mb_File;
    private javax.swing.JMenuItem mi_bajasRegistradas;
    private javax.swing.JMenuItem mi_catalogos;
    private javax.swing.JMenuItem mi_cerrarSesion;
    private javax.swing.JMenuItem mi_entradas;
    private javax.swing.JMenuItem mi_kardex;
    private javax.swing.JMenuItem mi_reportes;
    private javax.swing.JMenuItem mi_salidas;
    private javax.swing.JMenuItem mi_stockMaximo;
    private javax.swing.JMenuItem mi_stockMinimo;
    private javax.swing.JPanel pnl_cuerpo;
    // End of variables declaration//GEN-END:variables
}
