/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectobd2.vista;

import java.awt.CardLayout;
import proyectobd2.modelo.beans.Empleado;

/**
 *
 * @author basa2
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal(Empleado empleado) {
        initComponents();
        jLabel3.setText(empleado.getNombre());

        GUIEntradas panelEntradas = new GUIEntradas();
        GUISalidas panelSalidas = new GUISalidas();
        GUIInventario panelInventario = new GUIInventario();

        pnl_cuerpo.add(panelInventario, "inventario");
        pnl_cuerpo.add(panelEntradas, "entradas");
        pnl_cuerpo.add(panelSalidas, "salidas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 17), new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100));
        btn_entradas = new javax.swing.JButton();
        btn_salidas = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 270), new java.awt.Dimension(0, 270));
        jSeparator1 = new javax.swing.JSeparator();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jLabel3 = new javax.swing.JLabel();
        lb_tipoUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10));
        jButton8 = new javax.swing.JButton();
        pnl_cuerpo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(1024, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 15, 15, 15));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 574));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("GLOBAL");
        jLabel1.setAlignmentX(0.5F);
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("FINANCE");
        jLabel2.setAlignmentX(0.5F);
        jPanel1.add(jLabel2);
        jPanel1.add(filler1);

        btn_entradas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_entradas.setText("Entradas");
        btn_entradas.setAlignmentX(0.5F);
        btn_entradas.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_entradas.addActionListener(this::btn_entradasActionPerformed);
        jPanel1.add(btn_entradas);

        btn_salidas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_salidas.setText("Salidas");
        btn_salidas.setAlignmentX(0.5F);
        btn_salidas.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_salidas.addActionListener(this::btn_salidasActionPerformed);
        jPanel1.add(btn_salidas);

        btn_inventario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_inventario.setText("Inventario");
        btn_inventario.setAlignmentX(0.5F);
        btn_inventario.setMaximumSize(new java.awt.Dimension(180, 40));
        btn_inventario.addActionListener(this::btn_inventarioActionPerformed);
        jPanel1.add(btn_inventario);

        jButton5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton5.setText("Kardex");
        jButton5.setAlignmentX(0.5F);
        jButton5.setMaximumSize(new java.awt.Dimension(180, 40));
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton6.setText("Reportes");
        jButton6.setAlignmentX(0.5F);
        jButton6.setMaximumSize(new java.awt.Dimension(180, 40));
        jPanel1.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton7.setText("Catálogos");
        jButton7.setAlignmentX(0.5F);
        jButton7.setMaximumSize(new java.awt.Dimension(180, 40));
        jPanel1.add(jButton7);
        jPanel1.add(filler2);
        jPanel1.add(jSeparator1);
        jPanel1.add(filler3);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Nombre");
        jLabel3.setAlignmentX(0.5F);
        jPanel1.add(jLabel3);

        lb_tipoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lb_tipoUsuario.setText("tipoUsuario");
        lb_tipoUsuario.setAlignmentX(0.5F);
        jPanel1.add(lb_tipoUsuario);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setText("sucursal");
        jLabel5.setAlignmentX(0.5F);
        jPanel1.add(jLabel5);
        jPanel1.add(filler4);

        jButton8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(183, 0, 0));
        jButton8.setText("Cerrar Sesión");
        jButton8.setAlignmentX(0.5F);
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(199, 2, 2), 2, true));
        jButton8.setMaximumSize(new java.awt.Dimension(180, 40));
        jButton8.addActionListener(this::jButton8ActionPerformed);
        jPanel1.add(jButton8);
        jButton8.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        pnl_cuerpo.setBackground(new java.awt.Color(51, 0, 255));
        pnl_cuerpo.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnl_cuerpo, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btn_entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_entradasActionPerformed
        // Obtenemos el layout del panel contenedor
        CardLayout card = (CardLayout) pnl_cuerpo.getLayout();
        // Le pedimos que muestre el panel con el nombre que definimos antes
        card.show(pnl_cuerpo, "entradas");
    }//GEN-LAST:event_btn_entradasActionPerformed

    private void btn_salidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salidasActionPerformed

        CardLayout card = (CardLayout) pnl_cuerpo.getLayout();

        card.show(pnl_cuerpo, "salidas");
    }//GEN-LAST:event_btn_salidasActionPerformed

    private void btn_inventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inventarioActionPerformed
        CardLayout card = (CardLayout) pnl_cuerpo.getLayout();

        card.show(pnl_cuerpo, "inventario");
    }//GEN-LAST:event_btn_inventarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_entradas;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_salidas;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_tipoUsuario;
    private javax.swing.JPanel pnl_cuerpo;
    // End of variables declaration//GEN-END:variables
}
