/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista;

import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import proyectobd2.modelo.DAO.PeticionSalidaDAO;

/**
 *
 * @author endri
 */
public class GUISalidas extends javax.swing.JPanel {
 
    private JFrame framePadre = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);
    private PeticionSalidaDAO psDAO = new PeticionSalidaDAO();

    int idSucursal;

    /**
     * Creates new form Salidas
     * @param idSucursal
     */
    public GUISalidas(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        psDAO.obtenerSalidas(tb_salidas, idSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_departamento = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevaSalida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_salidas = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(874, 720));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Buscar por departamento:");
        jPanel1.add(jLabel1);

        txt_departamento.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txt_departamento);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);

        btn_nuevaSalida.setText("Nueva salida");
        btn_nuevaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevaSalida);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tb_salidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "DEPARTAMENTO", "ENCARGADO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_salidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_salidas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String departamento = txt_departamento.getText();
        if (!departamento.isEmpty()) {
            try {
                psDAO.buscar(departamento, idSucursal, tb_salidas);
            } catch (SQLException ex) {
            }

        } else {
            psDAO.obtenerSalidas(tb_salidas, this.idSucursal);
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tb_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_salidasMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tb_salidas.getSelectedRow();

            if (fila != -1) {
                String departamento = tb_salidas.getValueAt(fila, 1).toString();

                

                GUIArticulosPeticion articulosPeticion = new GUIArticulosPeticion(this.framePadre, true, departamento);
                articulosPeticion.setVisible(true);

            }
        }
    }//GEN-LAST:event_tb_salidasMouseClicked

    private void btn_nuevaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaSalidaActionPerformed
        GUINuevaSalida nuevaSalida = new GUINuevaSalida(this.framePadre, true);
        nuevaSalida.setVisible(true);
    }//GEN-LAST:event_btn_nuevaSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_nuevaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_salidas;
    private javax.swing.JTextField txt_departamento;
    // End of variables declaration//GEN-END:variables
}
