/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectobd2.vista;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.EmpleadoDAO;
import proyectobd2.modelo.HasheoContrasenia;
import proyectobd2.modelo.beans.Empleado;

/**
 *
 * @author endri
 */
public class InicioSesion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InicioSesion.class.getName());

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        grupoUsuario = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pf_contrasenia = new javax.swing.JPasswordField();
        btn_inicioSesion = new javax.swing.JButton();
        rb_usuarioCentral = new javax.swing.JRadioButton();
        rb_usuarioSalidas = new javax.swing.JRadioButton();
        rb_usuarioSucursal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión - Global Finance");
        setPreferredSize(new java.awt.Dimension(650, 500));

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Global Finance");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Sistema de control de almacenes");

        jLabel3.setText("Nombre");

        lb_usuario.setText("Ingresa tu nombre");
        lb_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_usuarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Contraseña");

        pf_contrasenia.setText("Ingresa tu contraseña");
        pf_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pf_contraseniaActionPerformed(evt);
            }
        });

        btn_inicioSesion.setBackground(new java.awt.Color(204, 0, 0));
        btn_inicioSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_inicioSesion.setText("Ingresar");
        btn_inicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioSesionActionPerformed(evt);
            }
        });

        grupoUsuario.add(rb_usuarioCentral);
        rb_usuarioCentral.setText("Usuario Central");
        rb_usuarioCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_usuarioCentralActionPerformed(evt);
            }
        });

        grupoUsuario.add(rb_usuarioSalidas);
        rb_usuarioSalidas.setText("Usuario Salidas");

        grupoUsuario.add(rb_usuarioSucursal);
        rb_usuarioSucursal.setText("Usuario Sucursal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pf_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(rb_usuarioSalidas)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rb_usuarioCentral, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rb_usuarioSucursal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_inicioSesion, lb_usuario, pf_contrasenia});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(pf_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(rb_usuarioCentral)
                .addGap(18, 18, 18)
                .addComponent(rb_usuarioSucursal)
                .addGap(18, 18, 18)
                .addComponent(rb_usuarioSalidas)
                .addGap(18, 18, 18)
                .addComponent(btn_inicioSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_inicioSesion, lb_usuario, pf_contrasenia});

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_usuarioActionPerformed

    private void pf_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pf_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pf_contraseniaActionPerformed

    private void btn_inicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioSesionActionPerformed
        String nombre = lb_usuario.getText();
        String contraseniaPlana = new String(pf_contrasenia.getPassword());

        if (!nombre.isEmpty() && !contraseniaPlana.isEmpty()) {
            String contraseniaHasheada = HasheoContrasenia.hashPassword(contraseniaPlana);

            EmpleadoDAO empleadodao = new EmpleadoDAO();
            try {
                HashMap<Empleado, ArrayList<String>> empleadoRoles = empleadodao.login(nombre, contraseniaHasheada);
                
                if (empleadoRoles != null) {
                    Empleado empleado = empleadoRoles.keySet().iterator().next();
                    //Mostrar la ventana que le corresponde al usuario
                    //VentanaPrincipal principal = new VentanaPrincipal(empleado);
                    //principal.setVisible(true);
                    ArrayList<String> roles = empleadoRoles.values().iterator().next();
                    if (roles.contains("Usuario central") && rb_usuarioCentral.isSelected()) {
                        //Mostrar la GUI de usuario central
                        this.dispose();
                    } else if (roles.contains("Usuario sucursal") && rb_usuarioSucursal.isSelected()) {
                        GUIPrincipal principal = new GUIPrincipal(empleado);
                        principal.setVisible(true);
                        this.dispose();
                    } else if (roles.contains("Usuario salidas") && rb_usuarioSalidas.isSelected()) {
                        //Mostrar el GUI de este usuario
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Selecciona un rol correcto", "Aviso", 1);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos", "Aviso", 1);
                    pf_contrasenia.setText("");
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error de la conexion con la base de datos", "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Los campos no pueden quedar vacíos", "Aviso", 1);
        }
    }//GEN-LAST:event_btn_inicioSesionActionPerformed

    private void rb_usuarioCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_usuarioCentralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_usuarioCentralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InicioSesion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicioSesion;
    private javax.swing.ButtonGroup grupoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField lb_usuario;
    private javax.swing.JPasswordField pf_contrasenia;
    private javax.swing.JRadioButton rb_usuarioCentral;
    private javax.swing.JRadioButton rb_usuarioSalidas;
    private javax.swing.JRadioButton rb_usuarioSucursal;
    // End of variables declaration//GEN-END:variables
}
