/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistasentradas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectobd2.modelo.DAO.PartidaPresupuestalDAO;
import proyectobd2.modelo.beans.PartidaPresupuestal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import proyectobd2.modelo.DAO.FacturaDAO;
import proyectobd2.modelo.DAO.ProveedorDAO;
import proyectobd2.modelo.beans.Factura;
import proyectobd2.modelo.beans.Item;
import proyectobd2.modelo.beans.Proveedor;

/**
 *
 * @author endri
 */
public class GUINuevaEntrada extends javax.swing.JDialog {

    private List<PartidaPresupuestal> listaPartidas;
    private List<Proveedor> listaProveedores;
    private double total = 0;

    PartidaPresupuestalDAO ppDAO = new PartidaPresupuestalDAO();
    ProveedorDAO proveedorDAO = new ProveedorDAO();
    FacturaDAO facDAO = new FacturaDAO();
    
    java.awt.Frame parent;

    /**
     * Creates new form GUINuevaEntrada
     *
     * @param parent
     * @param modal
     */
    public GUINuevaEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        initComponents();
        prepararComboBoxPartidas();
        prepararProveedores();

    }

    private void prepararComboBoxPartidas() {

        cbx_partidaPresupuestal.removeAllItems();

        try {
            listaPartidas = ppDAO.obtenerListaObjetos();

            for (PartidaPresupuestal pp : listaPartidas) {
                cbx_partidaPresupuestal.addItem(pp.getNombrePartida());
            }
            cbx_partidaPresupuestal.setSelectedIndex(-1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void prepararProveedores() {
        cbx_proveedores.removeAllItems();
        try {
            listaProveedores = proveedorDAO.obtenerListaObjetos();
            for (Proveedor p : listaProveedores) {
                cbx_proveedores.addItem(p.getRazonSocial());
            }
            cbx_proveedores.setSelectedIndex(-1);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_folioFactura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbx_proveedores = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbx_partidaPresupuestal = new javax.swing.JComboBox<>();
        btn_cancelar = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        spn_cantidad = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        spn_fecha = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_articulos = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        btn_agregarArticulo = new javax.swing.JButton();
        spn_costoUnitario = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        lb_precioTotal = new javax.swing.JLabel();
        lb_nombreItem = new javax.swing.JLabel();
        btn_buscarItem = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1050, 700));

        jPanel1.setPreferredSize(new java.awt.Dimension(1060, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Información de la factura");

        jLabel2.setText("Folio factura: ");

        txt_folioFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_folioFacturaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fecha:");

        jLabel6.setText("Proveedor:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Agregar artículos");

        jLabel8.setText("Cantidad:");

        jLabel9.setText("Nombre del artículo:");

        jLabel10.setText("Costo unitario:");

        jLabel11.setText("Partida presupuestal:");

        btn_cancelar.setBackground(new java.awt.Color(255, 0, 51));
        btn_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_guardar.setBackground(new java.awt.Color(0, 204, 0));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(0, 0, 0));
        btn_guardar.setText("Guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        spn_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        spn_fecha.setModel(new javax.swing.SpinnerDateModel());
        spn_fecha.setEditor(new javax.swing.JSpinner.DateEditor(spn_fecha, "dd/MM/yyyy"));

        tb_articulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Cantidad", "Costo unitario", "Partida presupuestal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_articulos);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Artículos");

        btn_agregarArticulo.setBackground(new java.awt.Color(0, 204, 0));
        btn_agregarArticulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_agregarArticulo.setForeground(new java.awt.Color(0, 0, 0));
        btn_agregarArticulo.setText("Agregar artículo");
        btn_agregarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarArticuloActionPerformed(evt);
            }
        });

        spn_costoUnitario.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        jLabel13.setText("Precio total:");

        lb_precioTotal.setText("*");

        lb_nombreItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_buscarItem.setText("Buscar item");
        btn_buscarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(236, 236, 236)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_folioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(cbx_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(spn_costoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11)
                    .addComponent(cbx_partidaPresupuestal, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(lb_precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cancelar)
                        .addGap(39, 39, 39)
                        .addComponent(btn_guardar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_agregarArticulo)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_buscarItem)
                            .addGap(67, 67, 67)
                            .addComponent(lb_nombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel12))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_folioFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(cbx_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscarItem)
                            .addComponent(lb_nombreItem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btn_agregarArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spn_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spn_costoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel11)
                        .addGap(6, 6, 6)
                        .addComponent(cbx_partidaPresupuestal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(lb_precioTotal))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_cancelar)
                            .addComponent(btn_guardar))))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean validarDatosArticulo() {
        if (lb_nombreItem.getText().trim().isEmpty()) {

            return false;
        }
        if ((Integer) spn_cantidad.getValue() <= 0.0) {

            return false;
        }
        if ((Double) spn_costoUnitario.getValue() <= 0.0) {

            return false;
        }
        if (cbx_partidaPresupuestal.getSelectedIndex() == -1) {

            return false;
        }
        return true;
    }
    private void btn_agregarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarArticuloActionPerformed

        if (!validarDatosArticulo()) {
            JOptionPane.showMessageDialog(this,
                    "Por favor completa los campos del artículo...",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tb_articulos.getModel();
        Object[] fila = new Object[4];
        fila[0] = lb_nombreItem.getText();       // Columna 1
        fila[1] = (Integer) spn_cantidad.getValue();   // Columna 2
        fila[2] = (Double) spn_costoUnitario.getValue();             // Columna 3 (Entero)
        fila[3] = cbx_partidaPresupuestal.getSelectedItem().toString();        // Columna 4 (Double)

        //Calcular total
        total += (Integer) spn_cantidad.getValue() * (Double) spn_costoUnitario.getValue();
        modelo.addRow(fila);

        lb_nombreItem.setText("");
        spn_cantidad.setValue(0);
        spn_costoUnitario.setValue(0.0);
        cbx_partidaPresupuestal.setSelectedIndex(-1);
        lb_precioTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btn_agregarArticuloActionPerformed

    private boolean validarDatosFactura() {
        if (txt_folioFactura.getText().trim().isEmpty()) {
            return false;
        }
        if (cbx_proveedores.getSelectedIndex() == -1) {

        }
        return true;
    }
    private void txt_folioFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_folioFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_folioFacturaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        if (tb_articulos.getRowCount() == 0 || !validarDatosFactura()) {

            JOptionPane.showMessageDialog(this,
                    "Por favor completa los campos...",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Factura f = prepararFactura();
        if(f == null){
            JOptionPane.showMessageDialog(this, "El folio ya está registrado...");
            return;
        }
        ArrayList<Item> items = new ArrayList<>();

        DefaultTableModel modelo = (DefaultTableModel) tb_articulos.getModel();

        for (int i = 0; i < modelo.getRowCount(); i++) {

            // 3. Extraemos los datos de cada columna especificando (fila, columna)
            // El índice 'i' representa la fila actual en el ciclo
            String descripcion = modelo.getValueAt(i, 0).toString();
            int cantidad = (Integer) modelo.getValueAt(i, 1);
            double costoUnitario = (Double) modelo.getValueAt(i, 2);

            try {
                PartidaPresupuestal partida = ppDAO.buscarPorNombre(modelo.getValueAt(i, 3).toString());
            } catch (SQLException ex) {
                return;

            }

            Item item = new Item();
//            item.set
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_buscarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarItemActionPerformed
        GUISeleccionarItem seleccionarItem = new GUISeleccionarItem(parent, false);
        seleccionarItem.setVisible(true);
    }//GEN-LAST:event_btn_buscarItemActionPerformed

    private Factura prepararFactura() {

        Factura f = new Factura();
        String folioFactura = txt_folioFactura.getText();
        try {
            if (facDAO.buscarPorFolio(folioFactura) == null) {
                
                return null;
            }
        } catch (SQLException ex) {

        }

        f.setFolioFactura(folioFactura);
        try {
            Date fechaSeleccionada = (Date) spn_fecha.getValue();
            f.setFechaFactura(fechaSeleccionada);
        } catch (ClassCastException ex) {
            ex.printStackTrace();
            return null;
        }

        try {
            f.setPrecioTotal(Double.valueOf(lb_precioTotal.getText()));
        } catch (NumberFormatException ex) {
            ex.printStackTrace();
            return null;
        }
        try {
            String razonSocial = cbx_proveedores.getSelectedItem().toString();
            Proveedor proveedor = proveedorDAO.buscarPorRazonSocial(razonSocial);

            f.setIdProveedor(proveedor.getIdProveedor());
        } catch (SQLException ex) {
            ex.printStackTrace();
            return null;
        }

        return f;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarArticulo;
    private javax.swing.JButton btn_buscarItem;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JComboBox<String> cbx_partidaPresupuestal;
    private javax.swing.JComboBox<String> cbx_proveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_nombreItem;
    private javax.swing.JLabel lb_precioTotal;
    private javax.swing.JSpinner spn_cantidad;
    private javax.swing.JSpinner spn_costoUnitario;
    private javax.swing.JSpinner spn_fecha;
    private javax.swing.JTable tb_articulos;
    private javax.swing.JTextField txt_folioFactura;
    // End of variables declaration//GEN-END:variables
}
