/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistasentradas;

import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import proyectobd2.modelo.DAO.ItemDAO;
import proyectobd2.modelo.beans.Item;

/**
 *
 * @author endri
 */
public class GUISeleccionarItem extends javax.swing.JDialog {

    private int idSucursal;
    private String itemSeleccionado = null;

    /**
     * Creates new form GUISeleccionarItem
     *
     * @param parent
     * @param modal
     * @param idSucursal
     */
    public GUISeleccionarItem(java.awt.Dialog parent, boolean modal, int idSucursal) {
        super(parent, modal);
        this.idSucursal = idSucursal;
        initComponents();
        llenarTabla();
        
        tb_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int fila = tb_items.getSelectedRow();
                    if (fila != -1) {
                        itemSeleccionado = tb_items.getValueAt(fila, 0).toString();
                        dispose();
                    }
                }
            }
        });
    }

    public String getItemSeleccionado() {
        return itemSeleccionado;
    }

    private void llenarTabla() {
        try {
            List<Item> listaItems = ItemDAO.obtenerListaPorSucursal(this.idSucursal);

            DefaultTableModel modelo = (DefaultTableModel) tb_items.getModel();
            modelo.setRowCount(0);
            int columnas = tb_items.getColumnCount();
            for (Item item : listaItems) {
                Object[] fila = new Object[columnas];

                fila[0] = item.getNombreItem();
                fila[1] = item.getExistencias();

                modelo.addRow(fila);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_nombreItem = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_items = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar por folio de factura:");
        jPanel1.add(jLabel1);

        txt_nombreItem.setMinimumSize(new java.awt.Dimension(150, 22));
        txt_nombreItem.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txt_nombreItem);

        btn_buscar.setText("Buscar");
        jPanel1.add(btn_buscar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tb_items.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre item", "Existencias "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_items);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
             * @param args the command line arguments
             */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_items;
    private javax.swing.JTextField txt_nombreItem;
    // End of variables declaration//GEN-END:variables
}
