/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistascatalogos;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.EmpleadoDAO;
import proyectobd2.modelo.DAO.RolDAO;
import static proyectobd2.modelo.HasheoContrasenia.hashPassword;
import proyectobd2.modelo.beans.Departamento;
import proyectobd2.modelo.beans.Empleado;
import proyectobd2.modelo.beans.Rol;
import proyectobd2.modelo.beans.Sucursal;

/**
 *
 * @author basa2
 */
public class NuevoEmpleado extends javax.swing.JDialog {
    String rol;
    private List<Sucursal> listaSucursales;
    private List<Departamento> listaDepartamentos;
    private List<Rol> roles;
    private Empleado empleadoModificar = null;
    /**
     * Creates new form NuevoEmpleado
     */
    public NuevoEmpleado(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<Departamento> listaDepartamentos, String rol) {
        super(parent, modal);
        this.rol = rol;
        initComponents();
        setLocationRelativeTo(parent);
        this.listaSucursales = listaSucursales;
        this.listaDepartamentos = listaDepartamentos;
        inicializarCombos();
        
    }
    
    public NuevoEmpleado(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<Departamento> listaDepartamentos, String rol, Empleado empleado) {
        super(parent, modal);
        this.rol = rol;
        initComponents();
        setLocationRelativeTo(parent);
        this.listaSucursales = listaSucursales;
        this.listaDepartamentos = listaDepartamentos;
        inicializarCombos();
        this.empleadoModificar=empleado;
        jLabel5.setText("Modificar empleado");
        jLabel6.setText("Actualiza la información necesaria");
        llenarParaModificar(empleado);
    }

    private void inicializarCombos(){
        llenarComboBoxSucursales(listaSucursales);
        llenarComboBoxDepartamentos(listaDepartamentos);
        llenarComboBoxRol();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfCorreoElectronico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfTelefonoFijo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfTelefonoCel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfContraseña = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbxSucursal = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxDepartamento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbxRol = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 550));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nuevo empleado");
        jPanel5.add(jLabel5);

        jLabel6.setText("Agrega toda la información requerida");
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 20));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jPanel2.add(txfNombre);

        jLabel2.setText("Apellidos");
        jPanel2.add(jLabel2);
        jPanel2.add(txfApellidos);

        jLabel3.setText("Correo Electrónico");
        jPanel2.add(jLabel3);
        jPanel2.add(txfCorreoElectronico);

        jLabel4.setText("Teléfono fijo");
        jPanel2.add(jLabel4);
        jPanel2.add(txfTelefonoFijo);

        jLabel7.setText("Telefono celular");
        jPanel2.add(jLabel7);
        jPanel2.add(txfTelefonoCel);

        jLabel8.setText("Contraseña Asignada");
        jPanel2.add(jLabel8);
        jPanel2.add(txfContraseña);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        jLabel9.setText("Sucursal");
        jPanel3.add(jLabel9);

        jPanel3.add(cbxSucursal);

        jLabel10.setText("Departamento");
        jPanel3.add(jLabel10);

        jPanel3.add(cbxDepartamento);

        jLabel11.setText("Rol");
        jPanel3.add(jLabel11);

        jPanel3.add(cbxRol);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(450, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel4.add(btnCancelar);
        jPanel4.add(filler1);

        btnGuardar.setText("Guardar");
        btnGuardar.setAlignmentX(0.5F);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(72, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txfNombre.getText().trim().isEmpty() || 
            txfApellidos.getText().trim().isEmpty() || 
            txfCorreoElectronico.getText().trim().isEmpty() || 
            cbxSucursal.getSelectedIndex() == -1 ||
            cbxDepartamento.getSelectedIndex() == -1 ||
            cbxRol.getSelectedIndex() == -1){
            JOptionPane.showMessageDialog(this, 
                    "Por favor, llene todos los campos obligatorios y seleccione las listas.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Empleado empleado = serializarEmpleado();
        
        if (empleadoModificar == null) {
            if (txfContraseña.getText().trim().isEmpty()){
                JOptionPane.showMessageDialog(this, 
                        "La contraseña es obligatoria para un nuevo empleado.", 
                        "Advertencia", 
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            int resultado = EmpleadoDAO.insertar(empleado);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Empleado guardado", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            empleado.setIdEmpleado(empleadoModificar.getIdEmpleado());
            if (empleado.getContrasenia() == null || empleado.getContrasenia().isEmpty()) {
                int actualizado = EmpleadoDAO.modificarsincontra(empleado);
                if (actualizado > 0) {
                    JOptionPane.showMessageDialog(this, "Empleado actualizado (sin contraseña)", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            } else {
                int actualizado = EmpleadoDAO.modificarConCOntra(empleado);
                if (actualizado > 0) {
                    JOptionPane.showMessageDialog(this, "Empleado actualizado (con contraseña)", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void llenarComboBoxSucursales(List<Sucursal> sucursales) {
        cbxSucursal.removeAllItems();
        for (Sucursal s : sucursales) {
            cbxSucursal.addItem(s.toString());
        }
    }

    private void llenarComboBoxDepartamentos(List<Departamento> departamentos) {
        cbxDepartamento.removeAllItems();
        for (Departamento d : departamentos) {
            cbxDepartamento.addItem(d.toString());
        }
    }
    
    private void llenarComboBoxRol() {
        cbxRol.removeAllItems();
        try{
            if("Usuario central".equals(rol)){
                roles = RolDAO.obtenerListaRoles();
                for (Rol r : roles) {
                    cbxRol.addItem(r.toString());
                }
            }
            if("Usuario sucursal".equals(rol)){
                roles = RolDAO.obtenerListaRolesSucursal();
                for (Rol r : roles) {
                    cbxRol.addItem(r.toString());
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Error de carga de roles", "Error", JOptionPane.ERROR_MESSAGE);
        }
       
    }
    
    private Empleado serializarEmpleado() {
        Empleado empleado = new Empleado();
        empleado.setNombre(txfNombre.getText().trim());
        empleado.setApellidos(txfApellidos.getText().trim());
        empleado.setCorreoElectronico(txfCorreoElectronico.getText().trim());
        String tlfFijo = txfTelefonoFijo.getText().trim();
        if(tlfFijo.isEmpty()){
            empleado.setTelefonoFijo(null);
        }else{
            empleado.setTelefonoFijo(tlfFijo);
        }
        empleado.setTelefonoCelular(txfTelefonoCel.getText().trim());
        
        if(empleadoModificar == null && !txfContraseña.getText().isBlank()){
            empleado.setContrasenia(hashPassword(txfContraseña.getText().trim()));
        }
        if(empleadoModificar != null && !txfContraseña.getText().isBlank()){
            empleado.setContrasenia(hashPassword(txfContraseña.getText().trim()));
        }
        if(empleadoModificar != null && txfContraseña.getText().isBlank()){
            empleado.setContrasenia(null);
        }
        int indiceSucursal = cbxSucursal.getSelectedIndex();
        if (indiceSucursal != -1) {
            Sucursal sucursalSeleccionada = listaSucursales.get(indiceSucursal);
            empleado.setIdSucursal(sucursalSeleccionada.getIdSucursal());
            empleado.setSucursal(sucursalSeleccionada.getNombreSucursal()); 
        }
        int indiceDepartamento = cbxDepartamento.getSelectedIndex();
        if (indiceDepartamento != -1) {
            Departamento departamentoSeleccionado = listaDepartamentos.get(indiceDepartamento);
            empleado.setIdDepartamentoEncar(departamentoSeleccionado.getIdDepartamento());
        }
        int indiceRol = cbxRol.getSelectedIndex();
        if (indiceRol != -1) {
            Rol rolSeleccionado = roles.get(indiceRol);
            empleado.setIdRol(rolSeleccionado.getIdRol());
        }
        empleado.setFechaRegistro(new java.sql.Date(System.currentTimeMillis()));
        return empleado;
    }
    
    private void llenarParaModificar(Empleado empleado){
        txfNombre.setText(empleado.getNombre());
        txfApellidos.setText(empleado.getApellidos());
        txfCorreoElectronico.setText(empleado.getCorreoElectronico());
        txfTelefonoFijo.setText(empleado.getTelefonoFijo());
        txfTelefonoCel.setText(empleado.getTelefonoCelular());
        for (int i = 0; i < listaSucursales.size(); i++) {
            if (listaSucursales.get(i).getIdSucursal() == empleado.getIdSucursal()) {
                cbxSucursal.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < listaDepartamentos.size(); i++) {
            if (listaDepartamentos.get(i).getIdDepartamento() == empleado.getIdDepartamentoEncar()) {
                cbxDepartamento.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < roles.size(); i++) {
            if (roles.get(i).getIdRol() == empleado.getIdRol()) {
                cbxRol.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxDepartamento;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txfApellidos;
    private javax.swing.JTextField txfContraseña;
    private javax.swing.JTextField txfCorreoElectronico;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefonoCel;
    private javax.swing.JTextField txfTelefonoFijo;
    // End of variables declaration//GEN-END:variables

}
