/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistascatalogos;

import java.util.List;
import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.ItemDAO;
import proyectobd2.modelo.beans.Item;
import proyectobd2.modelo.beans.PartidaPresupuestal;
import proyectobd2.modelo.beans.Sucursal;

/**
 *
 * @author basa2
 */
public class NuevoItem extends javax.swing.JDialog {
    private List<Sucursal> listaSucursales;
    private List<PartidaPresupuestal> listaPartidas;
    private Item itemModificar = null;
    /**
     * Creates new form NuevoItem
     */
    public NuevoItem(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<PartidaPresupuestal> listaPartidas) {
        super(parent, modal);
        initComponents();
        this.listaSucursales = listaSucursales;
        this.listaPartidas = listaPartidas;
        inicializarCombos();
        
        jLabel5.setText("Nuevo ítem");
        jLabel6.setText("Agrega toda la información requerida");
    }
    
    public NuevoItem(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<PartidaPresupuestal> listaPartidas, Item item) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.listaSucursales = listaSucursales;
        this.listaPartidas = listaPartidas;
        this.itemModificar = item;
        inicializarCombos();
        
        jLabel5.setText("Modificar ítem");
        jLabel6.setText("Actualiza la información necesaria");
        llenarParaModificar(item);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfPrecioUnitario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfStockMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfStockMax = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfExistencias = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txfDescripcion = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbxSucursal = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxPartida = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 550));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nuevo Item");
        jLabel5.setToolTipText("");
        jPanel5.add(jLabel5);

        jLabel6.setText("Agrega toda la información requerida");
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 20));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jPanel2.add(txfNombre);

        jLabel2.setText("Precio unitario");
        jPanel2.add(jLabel2);
        jPanel2.add(txfPrecioUnitario);

        jLabel3.setText("Stock mínimo");
        jPanel2.add(jLabel3);
        jPanel2.add(txfStockMin);

        jLabel4.setText("Stock máximo");
        jPanel2.add(jLabel4);
        jPanel2.add(txfStockMax);

        jLabel7.setText("Existencias");
        jPanel2.add(jLabel7);
        jPanel2.add(txfExistencias);

        jLabel8.setText("Descripcion de uso");
        jPanel2.add(jLabel8);
        jPanel2.add(txfDescripcion);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel9.setText("Sucursal");
        jPanel3.add(jLabel9);

        jPanel3.add(cbxSucursal);

        jLabel10.setText("Partida presupuestal");
        jPanel3.add(jLabel10);

        jPanel3.add(cbxPartida);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(450, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel4.add(btnCancelar);
        jPanel4.add(filler1);

        btnGuardar.setText("Guardar");
        btnGuardar.setAlignmentX(0.5F);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(72, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txfNombre.getText().trim().isEmpty() || 
            txfPrecioUnitario.getText().trim().isEmpty() || 
            txfStockMin.getText().trim().isEmpty() || 
            txfStockMax.getText().trim().isEmpty() || 
            txfExistencias.getText().trim().isEmpty() || 
            txfDescripcion.getText().trim().isEmpty() || 
            cbxSucursal.getSelectedIndex() == -1 || 
            cbxPartida.getSelectedIndex() == -1) {
            
            JOptionPane.showMessageDialog(this, 
                    "Por favor, llene todos los campos obligatorios y seleccione las listas.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        double precio;
        int stockMin;
        int stockMax;
        int existencias;
        try {
            precio = Double.parseDouble(txfPrecioUnitario.getText().trim());
            stockMin = Integer.parseInt(txfStockMin.getText().trim());
            stockMax = Integer.parseInt(txfStockMax.getText().trim());
            existencias = Integer.parseInt(txfExistencias.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "Precio unitario y stocks deben ser valores numéricos válidos.", 
                    "Error de formato", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        Item item = serializarItem(precio, stockMin, stockMax, existencias);
        if (itemModificar == null) {
            int resultado = ItemDAO.insertar(item);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Ítem guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            item.setIdItem(itemModificar.getIdItem());
            int actualizado = ItemDAO.modificarsinEstado(item);
            if (actualizado > 0) {
                JOptionPane.showMessageDialog(this, "Ítem actualizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void inicializarCombos() {
        llenarComboBoxSucursales(listaSucursales);
        llenarComboBoxPartidas(listaPartidas);
    }
    
    private void llenarComboBoxSucursales(List<Sucursal> sucursales) {
        cbxSucursal.removeAllItems();
        for (Sucursal s : sucursales) {
            cbxSucursal.addItem(s.toString());
        }
    }

    private void llenarComboBoxPartidas(List<PartidaPresupuestal> partidas) {
        cbxPartida.removeAllItems();
        for (PartidaPresupuestal p : partidas) {
            cbxPartida.addItem(p.toString());
        }
    }

    private Item serializarItem(double precio, int sMin, int sMax, int exis) {
        Item i = new Item();
        i.setNombreItem(txfNombre.getText().trim());
        i.setPrecioUnitario(precio);
        i.setStockMinimo(sMin);
        i.setStockMaximo(sMax);
        i.setExistencias(exis);
        i.setDescripcionUso(txfDescripcion.getText().trim());
        
        int indiceSuc = cbxSucursal.getSelectedIndex();
        if (indiceSuc != -1) {
            i.setIdSucursal(listaSucursales.get(indiceSuc).getIdSucursal());
        }
        
        int indicePartida = cbxPartida.getSelectedIndex();
        if (indicePartida != -1) {
            i.setIdPartidaPresupuestal(listaPartidas.get(indicePartida).getIdPartidaPresupuestal());
        }
        return i;
    }

    private void llenarParaModificar(Item i) {
        txfNombre.setText(i.getNombreItem());
        txfPrecioUnitario.setText(String.valueOf(i.getPrecioUnitario()));
        txfStockMin.setText(String.valueOf(i.getStockMinimo()));
        txfStockMax.setText(String.valueOf(i.getStockMaximo()));
        txfExistencias.setText(String.valueOf(i.getExistencias()));
        txfDescripcion.setText(i.getDescripcionUso());
        
        // Autoseleccionar sucursal
        for (int j = 0; j < listaSucursales.size(); j++) {
            if (listaSucursales.get(j).getIdSucursal() == i.getIdSucursal()) {
                cbxSucursal.setSelectedIndex(j);
                break;
            }
        }
        
        // Autoseleccionar partida presupuestal
        for (int j = 0; j < listaPartidas.size(); j++) {
            if (listaPartidas.get(j).getIdPartidaPresupuestal() == i.getIdPartidaPresupuestal()) {
                cbxPartida.setSelectedIndex(j);
                break;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxPartida;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txfDescripcion;
    private javax.swing.JTextField txfExistencias;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPrecioUnitario;
    private javax.swing.JTextField txfStockMax;
    private javax.swing.JTextField txfStockMin;
    // End of variables declaration//GEN-END:variables
}
