/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistascatalogos;

import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.ProveedorDAO;
import proyectobd2.modelo.beans.Proveedor;

/**
 *
 * @author basa2
 */
public class NuevoProveedor extends javax.swing.JDialog{
    private Proveedor proveedorModificar = null;
    /**
     * Creates new form NuevoProveedor
     */
    public NuevoProveedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel5.setText("Nuevo proveedor");
        jLabel6.setText("Agrega toda la información requerida");
    }
    
    public NuevoProveedor(java.awt.Frame parent, boolean modal, Proveedor proveedor) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.proveedorModificar = proveedor;
        
        jLabel5.setText("Modificar proveedor");
        jLabel6.setText("Actualiza la información necesaria");
        llenarParaModificar(proveedor);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txfCorreoElectronico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfTelefonoFijo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nuevo proveedor");
        jPanel5.add(jLabel5);

        jLabel6.setText("Agrega toda la información requerida");
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 20));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel1.setText("Razón Social");
        jPanel2.add(jLabel1);
        jPanel2.add(txfNombre);

        jLabel2.setText("RFC");
        jPanel2.add(jLabel2);
        jPanel2.add(txfApellidos);

        jLabel3.setText("Domicilio fiscal");
        jPanel2.add(jLabel3);
        jPanel2.add(txfCorreoElectronico);

        jLabel4.setText("Teléfono");
        jPanel2.add(jLabel4);
        jPanel2.add(txfTelefonoFijo);

        jPanel1.add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(450, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel4.add(btnCancelar);
        jPanel4.add(filler1);

        btnGuardar.setText("Guardar");
        btnGuardar.setAlignmentX(0.5F);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(72, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txfNombre.getText().trim().isEmpty() || 
            txfApellidos.getText().trim().isEmpty() || 
            txfCorreoElectronico.getText().trim().isEmpty() || 
            txfTelefonoFijo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, llene todos los campos obligatorios.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        Proveedor p = serializarProveedor();
        if (proveedorModificar == null) {
            int resultado = ProveedorDAO.insertar(p);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Proveedor guardado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            p.setIdProveedor(proveedorModificar.getIdProveedor());
            int actualizado = ProveedorDAO.modificar(p);
            if (actualizado > 0) {
                JOptionPane.showMessageDialog(this, "Proveedor actualizado con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private Proveedor serializarProveedor() {
        Proveedor p = new Proveedor();
        p.setRazonSocial(txfNombre.getText().trim());
        p.setRFCProveedor(txfApellidos.getText().trim());
        p.setDomicilioFiscal(txfCorreoElectronico.getText().trim());
        p.setTelefono(txfTelefonoFijo.getText().trim());
        return p;
    }

    private void llenarParaModificar(Proveedor p) {
        txfNombre.setText(p.getRazonSocial());
        txfApellidos.setText(p.getRFCProveedor());
        txfCorreoElectronico.setText(p.getDomicilioFiscal());
        txfTelefonoFijo.setText(p.getTelefono());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txfApellidos;
    private javax.swing.JTextField txfCorreoElectronico;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefonoFijo;
    // End of variables declaration//GEN-END:variables
}
