/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistascatalogos;

import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.PartidaPresupuestalDAO;
import proyectobd2.modelo.beans.PartidaPresupuestal;

/**
 *
 * @author basa2
 */
public class NuevaPartida extends javax.swing.JDialog {
    private PartidaPresupuestal partidaModificar = null;
    /**
     * Creates new form NuevaPartida
     */
    public NuevaPartida(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabel5.setText("Nueva partida presupuestal");
        jLabel6.setText("Agrega toda la información requerida");
    }

    public NuevaPartida(java.awt.Frame parent, boolean modal, PartidaPresupuestal partida) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.partidaModificar = partida;
        
        jLabel5.setText("Modificar partida presupuestal");
        jLabel6.setText("Actualiza la información necesaria");
        llenarParaModificar(partida);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfPresupuesto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnGuardar = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(450, 550));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nueva partida presupuestal");
        jPanel5.add(jLabel5);

        jLabel6.setText("Agrega toda la información requerida");
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 20));
        jPanel2.setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jPanel2.add(txfNombre);

        jLabel2.setText("Presupuesto");
        jPanel2.add(jLabel2);
        jPanel2.add(txfPresupuesto);

        jPanel1.add(jPanel2);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(450, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel4.add(btnCancelar);
        jPanel4.add(filler1);

        btnGuardar.setText("Guardar");
        btnGuardar.setAlignmentX(0.5F);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(72, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txfNombre.getText().trim().isEmpty() || txfPresupuesto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Por favor, llene todos los campos obligatorios.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        double presupuesto;
        try {
            presupuesto = Double.parseDouble(txfPresupuesto.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                    "El presupuesto debe ser un valor numérico válido.", 
                    "Error de formato", 
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        PartidaPresupuestal partida = serializarPartida(presupuesto);

        if (partidaModificar == null) {
            int resultado = PartidaPresupuestalDAO.insertar(partida);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Partida guardada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            partida.setIdPartidaPresupuestal(partidaModificar.getIdPartidaPresupuestal());
            int actualizado = PartidaPresupuestalDAO.modificar(partida);
            if (actualizado > 0) {
                JOptionPane.showMessageDialog(this, "Partida actualizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private PartidaPresupuestal serializarPartida(double presupuesto) {
        PartidaPresupuestal p = new PartidaPresupuestal();
        p.setNombrePartida(txfNombre.getText().trim());
        p.setPresupuesto(presupuesto);
        return p;
    }

    private void llenarParaModificar(PartidaPresupuestal p) {
        txfNombre.setText(p.getNombrePartida());
        txfPresupuesto.setText(String.valueOf(p.getPresupuesto()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPresupuesto;
    // End of variables declaration//GEN-END:variables
}
