/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistascatalogos;

import java.util.List;
import javax.swing.JOptionPane;
import proyectobd2.modelo.DAO.DepartamentoDAO;
import proyectobd2.modelo.beans.Departamento;
import proyectobd2.modelo.beans.Empleado;
import proyectobd2.modelo.beans.Sucursal;

/**
 *
 * @author basa2
 */
public class NuevoDepartamento extends javax.swing.JDialog {
    private List<Sucursal> listaSucursales;
    private List<Empleado> listaEncargados;
    private Departamento departamentoModificar = null;
    /**
     * Creates new form NuevoDepartamento
     */
    public NuevoDepartamento(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<Empleado> listaEncargados) {
        super(parent, modal);
        initComponents();
        this.listaSucursales = listaSucursales;
        this.listaEncargados = listaEncargados;
        inicializarCombos();
        jLabel5.setText("Nuevo departamento");
        jLabel6.setText("Agrega toda la información requerida");
    }
    
    public NuevoDepartamento(java.awt.Frame parent, boolean modal, List<Sucursal> listaSucursales, List<Empleado> listaEncargados, Departamento departamento) {
        super(parent, modal);
        initComponents();
        this.listaSucursales = listaSucursales;
        this.listaEncargados = listaEncargados;
        this.departamentoModificar = departamento;
        inicializarCombos();
        jLabel5.setText("Modificar departamento");
        jLabel6.setText("Actualiza la información necesaria");
        llenarParaModificar(departamento);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cbxSucursal = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbxEncargado = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0), new java.awt.Dimension(30, 0));
        btnGuardar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 300));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 1, 1));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 60));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nuevo departamento");
        jPanel5.add(jLabel5);

        jLabel6.setText("Agrega toda la información requerida");
        jPanel5.add(jLabel6);

        jPanel1.add(jPanel5);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 20));
        jPanel2.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        jLabel1.setText("Nombre");
        jPanel2.add(jLabel1);
        jPanel2.add(txfNombre);

        jPanel1.add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 5, 15, 5));
        jPanel3.setAlignmentX(0.0F);
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jLabel9.setText("Sucursal");
        jPanel3.add(jLabel9);

        jPanel3.add(cbxSucursal);

        jLabel10.setText("Encargado");
        jPanel3.add(jLabel10);

        jPanel3.add(cbxEncargado);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 10, 10));
        jPanel4.setAlignmentX(0.0F);
        jPanel4.setMaximumSize(new java.awt.Dimension(450, 100));
        jPanel4.setPreferredSize(new java.awt.Dimension(450, 60));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        btnCancelar.setText("Cancelar");
        btnCancelar.setAlignmentX(0.5F);
        btnCancelar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        jPanel4.add(btnCancelar);
        jPanel4.add(filler1);

        btnGuardar.setText("Guardar");
        btnGuardar.setAlignmentX(0.5F);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(72, 30));
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);
        jPanel4.add(btnGuardar);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txfNombre.getText().trim().isEmpty() || 
            cbxSucursal.getSelectedIndex() == -1 || 
            cbxEncargado.getSelectedIndex() == -1) {
            
            JOptionPane.showMessageDialog(this, 
                    "Por favor, llene todos los campos obligatorios y seleccione las listas.", 
                    "Advertencia", 
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        Departamento dep = serializarDepartamento();

        if (departamentoModificar == null) {
            int resultado = DepartamentoDAO.insertar(dep);
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Departamento guardado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            dep.setIdDepartamento(departamentoModificar.getIdDepartamento());
            int resultado = DepartamentoDAO.modificar(dep);
            
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "Departamento actualizado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void inicializarCombos() {
        llenarComboBoxSucursales(listaSucursales);
        llenarComboBoxEncargados(listaEncargados);
    }
    
    private void llenarComboBoxSucursales(List<Sucursal> sucursales) {
        cbxSucursal.removeAllItems();
        for (Sucursal s : sucursales) {
            cbxSucursal.addItem(s.toString());
        }
    }

    private void llenarComboBoxEncargados(List<Empleado> encargados) {
        cbxEncargado.removeAllItems();
        for (Empleado e : encargados) {
            cbxEncargado.addItem(e.toString()); 
        }
    }

    private Departamento serializarDepartamento() {
        Departamento dep = new Departamento();
        dep.setNombreDepartamento(txfNombre.getText().trim());
        
        int indiceSuc = cbxSucursal.getSelectedIndex();
        if (indiceSuc != -1) {
            dep.setIdSucursal(listaSucursales.get(indiceSuc).getIdSucursal());
        }
        
        int indiceEnc = cbxEncargado.getSelectedIndex();
        if (indiceEnc != -1) {
            dep.setIdEncargado(listaEncargados.get(indiceEnc).getIdEmpleado());
        }
        
        return dep;
    }
    
    private void llenarParaModificar(Departamento dep) {
        txfNombre.setText(dep.getNombreDepartamento());
        for (int i = 0; i < listaSucursales.size(); i++) {
            if (listaSucursales.get(i).getIdSucursal() == dep.getIdSucursal()) {
                cbxSucursal.setSelectedIndex(i);
                break;
            }
        }
        for (int i = 0; i < listaEncargados.size(); i++) {
            if (listaEncargados.get(i).getIdEmpleado() == dep.getIdEncargado()) {
                cbxEncargado.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxEncargado;
    private javax.swing.JComboBox<String> cbxSucursal;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
