package proyectobd2.vista.vistassalidas;

import java.awt.CardLayout;
import java.sql.SQLException;
import proyectobd2.modelo.DAO.SucursalDAO;
import proyectobd2.modelo.beans.Empleado;

/**
 *
 * @author basa2
 */
public class GUIPrincipalSalidas extends javax.swing.JFrame {

    private CardLayout card = null;

    /**
     * Creates new form GUIPrincipal
     *
     * @param empleado
     * @throws java.sql.SQLException
     */
    public GUIPrincipalSalidas(Empleado empleado) throws SQLException {
        initComponents();
        
        lb_nombreEmpleado.setText(empleado.getNombre() + empleado.getApellidos());
        int idSucursal = empleado.getIdSucursal();
        lb_nombreSucursal.setText(SucursalDAO.buscar(idSucursal).getNombreSucursal());
        card = (CardLayout) pnl_cuerpo.getLayout();

        GUISalidasUsuarioSalidas panelSalidas = new GUISalidasUsuarioSalidas(idSucursal);

        pnl_cuerpo.add(panelSalidas, "salidas");
        

        card.show(pnl_cuerpo, "salidas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_cuerpo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_nombreEmpleado = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 20), new java.awt.Dimension(50, 20), new java.awt.Dimension(30, 20));
        jLabel2 = new javax.swing.JLabel();
        lb_nombreSucursal = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 20), new java.awt.Dimension(50, 20), new java.awt.Dimension(30, 20));
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        mi_salidas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_cerrarSesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(227, 227, 227));
        setMinimumSize(new java.awt.Dimension(977, 550));

        pnl_cuerpo.setMinimumSize(new java.awt.Dimension(825, 550));
        pnl_cuerpo.setPreferredSize(new java.awt.Dimension(1080, 720));
        pnl_cuerpo.setLayout(new java.awt.CardLayout());
        getContentPane().add(pnl_cuerpo, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Empelado:");
        jPanel1.add(jLabel1);

        lb_nombreEmpleado.setText("*");
        jPanel1.add(lb_nombreEmpleado);
        jPanel1.add(filler1);

        jLabel2.setText("Sucursal: ");
        jPanel1.add(jLabel2);

        lb_nombreSucursal.setText("*");
        jPanel1.add(lb_nombreSucursal);
        jPanel1.add(filler2);

        jLabel3.setText("Usuario Salidas");
        jPanel1.add(jLabel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jMenu2.setText("Categorías");

        mi_salidas.setText("Salidas");
        mi_salidas.addActionListener(this::mi_salidasActionPerformed);
        jMenu2.add(mi_salidas);
        jMenu2.add(jSeparator1);

        mi_cerrarSesion.setText("Cerrar sesión");
        mi_cerrarSesion.addActionListener(this::mi_cerrarSesionActionPerformed);
        jMenu2.add(mi_cerrarSesion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_cerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_cerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_mi_cerrarSesionActionPerformed

    private void mi_salidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_salidasActionPerformed
        card = (CardLayout) pnl_cuerpo.getLayout();

        card.show(pnl_cuerpo, "salidas");
    }//GEN-LAST:event_mi_salidasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lb_nombreEmpleado;
    private javax.swing.JLabel lb_nombreSucursal;
    private javax.swing.JMenuItem mi_cerrarSesion;
    private javax.swing.JMenuItem mi_salidas;
    private javax.swing.JPanel pnl_cuerpo;
    // End of variables declaration//GEN-END:variables
}
