/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistassalidas;

import java.awt.Frame;
import java.awt.Window;
import proyectobd2.vista.vistassucursal.vistassalidas.*;
import proyectobd2.vista.GUIArticulosPeticion;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectobd2.modelo.DAO.PeticionSalidaDAO;

/**
 *
 * @author endri
 */
public class GUISalidasUsuarioSalidas extends javax.swing.JPanel {

    private JFrame framePadre = (JFrame) SwingUtilities.getAncestorOfClass(JFrame.class, this);

    int idSucursal;
    private List<Integer> idsPeticiones = new ArrayList<>();

    /**
     * Creates new form Salidas
     *
     * @param idSucursal
     */
    public GUISalidasUsuarioSalidas(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        llenarTabla("Todos");
    }

    private void llenarTabla(String tipo) {
        DefaultTableModel modelo = (DefaultTableModel) tb_salidas.getModel();
        modelo.setRowCount(0);
        idsPeticiones.clear();
        List<Object[]> datos = PeticionSalidaDAO.obtenerSalidas(idSucursal, tipo);
        for (Object[] fila : datos) {
            idsPeticiones.add((Integer) fila[0]);
            modelo.addRow(new Object[]{fila[1], fila[2], fila[3], fila[4]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_departamento = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_nuevaSalida = new javax.swing.JButton();
        tbtn_mostrarPendientes = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_salidas = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_editar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(874, 720));
        setLayout(new java.awt.BorderLayout());

        txt_titulo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_titulo.setText("PANEL SALIDAS");
        jPanel1.add(txt_titulo);

        jLabel1.setText("Buscar por departamento:");
        jPanel1.add(jLabel1);

        txt_departamento.setPreferredSize(new java.awt.Dimension(150, 22));
        jPanel1.add(txt_departamento);

        btn_buscar.setText("Buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar);

        btn_nuevaSalida.setText("Nueva salida");
        btn_nuevaSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevaSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_nuevaSalida);

        tbtn_mostrarPendientes.setText("MostrarPendientes");
        tbtn_mostrarPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtn_mostrarPendientesActionPerformed(evt);
            }
        });
        jPanel1.add(tbtn_mostrarPendientes);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        tb_salidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA", "DEPARTAMENTO", "ENCARGADO", "ESTADO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_salidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_salidas);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btn_editar.setBackground(new java.awt.Color(255, 0, 0));
        btn_editar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_editar);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        String departamento = txt_departamento.getText();

        if (!departamento.isEmpty()) {
            try {
                DefaultTableModel modelo = (DefaultTableModel) tb_salidas.getModel();
                modelo.setRowCount(0);
                idsPeticiones.clear();
                List<Object[]> datos = PeticionSalidaDAO.buscar(departamento, idSucursal);
                for (Object[] fila : datos) {
                    idsPeticiones.add((Integer) fila[0]);
                    modelo.addRow(new Object[]{fila[1], fila[2], fila[3], fila[4]});
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }

        } else {
            llenarTabla("Pendiente");
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tb_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_salidasMouseClicked
        if (evt.getClickCount() == 2) {
            int fila = tb_salidas.getSelectedRow();

            if (fila != -1) {
                int modelRow = tb_salidas.convertRowIndexToModel(fila);
                int idPeticion = idsPeticiones.get(modelRow);

                GUIArticulosPeticion articulosPeticion = new GUIArticulosPeticion(this.framePadre, true, idPeticion);
                articulosPeticion.setVisible(true);

            }
        }
    }//GEN-LAST:event_tb_salidasMouseClicked

    private void btn_nuevaSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevaSalidaActionPerformed
        GUINuevaSalida nuevaSalida = new GUINuevaSalida(this.framePadre, true, this.idSucursal);
        nuevaSalida.setVisible(true);
    }//GEN-LAST:event_btn_nuevaSalidaActionPerformed

    private void tbtn_mostrarPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtn_mostrarPendientesActionPerformed
        if (tbtn_mostrarPendientes.isSelected()) {
            llenarTabla("Pendiente");

        } else {
            llenarTabla("Todos");
        }

    }//GEN-LAST:event_tbtn_mostrarPendientesActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        int fila = tb_salidas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una petición primero");
            return;
        }
        int modelRow = tb_salidas.convertRowIndexToModel(fila);
        String estado = (String) tb_salidas.getValueAt(fila, 3);
        if (!estado.equalsIgnoreCase("EN ESPERA")) {
            JOptionPane.showMessageDialog(this, "Selecciona una petición con estado 'EN ESPERA'");
            return;
        }
        int idPeticion = idsPeticiones.get(modelRow);
        Window ventanaPadre = SwingUtilities.getWindowAncestor(this);
        GUIEditarSalida editarSalida = new GUIEditarSalida((Frame) ventanaPadre, true, this.idSucursal, idPeticion);
        editarSalida.setVisible(true);

        if (tbtn_mostrarPendientes.isSelected()) {
            llenarTabla("Pendiente");
        } else {
            llenarTabla("Todos");
        }
    }//GEN-LAST:event_btn_editarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_nuevaSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_salidas;
    private javax.swing.JToggleButton tbtn_mostrarPendientes;
    private javax.swing.JTextField txt_departamento;
    private javax.swing.JLabel txt_titulo;
    // End of variables declaration//GEN-END:variables
}
