/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistasreporte;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectobd2.modelo.DAO.PartidaPresupuestalDAO;
import proyectobd2.modelo.DAO.ReporteEntradaDAO;
import proyectobd2.modelo.DAO.ReporteSalidaDAO;
import proyectobd2.modelo.beans.PartidaPresupuestal;
import proyectobd2.modelo.beans.ReporteEntradas;
import proyectobd2.modelo.beans.ReporteSalidas;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author basa2
 */
public class GUIReportes extends javax.swing.JPanel {
    int idSucursal;
    String rol;
    private List<ReporteEntradas> listaIngresos;
    private List<ReporteSalidas> listaEgresos;
    PartidaPresupuestalDAO partidaDao = new PartidaPresupuestalDAO();
    private List<PartidaPresupuestal> listaParPre;
    private SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form GUIReportes
     */
    public GUIReportes(int idSucursal, String rol) {
        initComponents();
        this.idSucursal = idSucursal;
        this.rol = rol;
        llenarCombo();
        cargarTodosLosDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfFechaInicio = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txfFechaFin = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbxPartidaPresupuestal = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        btnExportarPdfIngresos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblIngresos = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        btnExportarPdfEgresos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEgresos = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setMinimumSize(new java.awt.Dimension(1000, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1260, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1260, 80));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Consultas y Reportes");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Visualice y exporte reportes financieros del sistema");
        jPanel1.add(jLabel2);

        add(jPanel1);

        jPanel2.setAlignmentX(0.0F);
        jPanel2.setLayout(new java.awt.GridLayout(2, 2));

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Fecha inicio");
        jPanel4.add(jLabel3);

        txfFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txfFechaInicio.setAlignmentX(0.0F);
        jPanel4.add(txfFechaInicio);

        jPanel2.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Fecha fin");
        jPanel5.add(jLabel4);

        txfFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        txfFechaFin.setAlignmentX(0.0F);
        jPanel5.add(txfFechaFin);

        jPanel2.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Partida presupuestal");
        jPanel6.add(jLabel5);

        cbxPartidaPresupuestal.setAlignmentX(0.0F);
        jPanel6.add(cbxPartidaPresupuestal);

        jPanel2.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel7.setLayout(new java.awt.BorderLayout());

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);
        jPanel7.add(btnBuscar, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel7);

        add(jPanel2);

        jPanel3.setAlignmentX(0.0F);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        btnExportarPdfIngresos.setText("Exportar a PDF");
        btnExportarPdfIngresos.setPreferredSize(new java.awt.Dimension(75, 40));
        btnExportarPdfIngresos.addActionListener(this::btnExportarPdfIngresosActionPerformed);
        jPanel8.add(btnExportarPdfIngresos, java.awt.BorderLayout.PAGE_START);

        tblIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Fecha", "Proveedor", "RFC", "Partida presupuestal", "Artículo", "Cantidad", "PrecioUnitario", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblIngresos);

        jPanel8.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Ingresos", jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        btnExportarPdfEgresos.setText("Exportar a PDF");
        btnExportarPdfEgresos.setMargin(new java.awt.Insets(2, 14, 10, 14));
        btnExportarPdfEgresos.setPreferredSize(new java.awt.Dimension(75, 40));
        btnExportarPdfEgresos.addActionListener(this::btnExportarPdfEgresosActionPerformed);
        jPanel9.add(btnExportarPdfEgresos, java.awt.BorderLayout.PAGE_START);

        tblEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Departamento", "Encargado", "Descripcion", "Artículo", "Partida presupuestal", "Cantidad", "Precio Unitario", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEgresos);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Egresos", jPanel9);

        jPanel3.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarPdfEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfEgresosActionPerformed
        String titulo = generarTitulo("Egresos");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte de Egresos");
        fileChooser.setSelectedFile(new java.io.File("Reporte_Egresos.pdf"));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) ruta += ".pdf";
            exportarPDF((DefaultTableModel) tblEgresos.getModel(), titulo, ruta);
        }
    }//GEN-LAST:event_btnExportarPdfEgresosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        aplicarFiltros();
        txfFechaInicio.setText("");
        txfFechaFin.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnExportarPdfIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPdfIngresosActionPerformed
        String titulo = generarTitulo("Ingresos");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Guardar reporte de Ingresos");
        fileChooser.setSelectedFile(new java.io.File("Reporte_Ingresos.pdf"));
        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String ruta = fileChooser.getSelectedFile().getAbsolutePath();
            if (!ruta.toLowerCase().endsWith(".pdf")) ruta += ".pdf";
            exportarPDF((DefaultTableModel) tblIngresos.getModel(), titulo, ruta);
        }
    }//GEN-LAST:event_btnExportarPdfIngresosActionPerformed

    private void llenarCombo(){
        try{
            cbxPartidaPresupuestal.removeAllItems();
            cbxPartidaPresupuestal.addItem("Todas las partidas");
            List<PartidaPresupuestal> lista = partidaDao.obtenerListaObjetos();
            for (PartidaPresupuestal p : lista) {
                cbxPartidaPresupuestal.addItem(p);
            }
        }catch (SQLException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());

        }
    }
    
    private void cargarTodosLosDatos() {
        try {
            if ("Usuario central".equals(rol)){
                ReporteEntradaDAO daoEntrada = new ReporteEntradaDAO();
                this.listaIngresos = daoEntrada.obtenerTodo();
                actualizarTablaIngresos(this.listaIngresos);
                ReporteSalidaDAO daoSalida = new ReporteSalidaDAO();
                this.listaEgresos = daoSalida.obtenerTodo();
                actualizarTablaEgresos(this.listaEgresos);
            }
            if ("Usuario sucursal".equals(rol) || "Usuario salidas".equals(rol)){
                ReporteEntradaDAO daoEntrada = new ReporteEntradaDAO();
                this.listaIngresos = daoEntrada.obtenerPorId(idSucursal);
                actualizarTablaIngresos(this.listaIngresos);
                ReporteSalidaDAO daoSalida = new ReporteSalidaDAO();
                this.listaEgresos = daoSalida.obtenerPorId(idSucursal);
                actualizarTablaEgresos(this.listaEgresos);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar datos: " + e.getMessage());
        }
    }
    
    private void actualizarTablaIngresos(List<ReporteEntradas> lista) {
        DefaultTableModel model = (DefaultTableModel) tblIngresos.getModel();
        model.setRowCount(0);
        for (ReporteEntradas e : lista) {
            model.addRow(new Object[]{
                e.getFolio(), e.getFecha(), e.getProvedor(),  e.getRfc(),                
                e.getPartidaPresupuestal(), e.getArticulo(), e.getCantidad(),           
                e.getPrecioUnitario(), e.getSubtotal()            
            });
        }
    }
    
    private void actualizarTablaEgresos(List<ReporteSalidas> lista) {
        DefaultTableModel model = (DefaultTableModel) tblEgresos.getModel();
        model.setRowCount(0);
        for (ReporteSalidas s : lista) {
            model.addRow(new Object[]{
                s.getFecha(), s.getDepartamento(), s.getEncargado(),         
                s.getDescripcion(), s.getArticulo(), s.getPartidaPresupuestal(),
                s.getCatidad(), s.getPrecioUnitario(), s.getSubtotal()          
            });
        }
    }

    private void aplicarFiltros() {
        try {
            String textoFechaI = txfFechaInicio.getText().trim();
            String textoFechaF = txfFechaFin.getText().trim();
            Date fechaI = textoFechaI.isEmpty() ? null : formato.parse(textoFechaI);
            Date fechaF = textoFechaF.isEmpty() ? null : formato.parse(textoFechaF);
            Object obj = cbxPartidaPresupuestal.getSelectedItem();
            String partidaFiltro = null;
            if (obj instanceof PartidaPresupuestal) {
                PartidaPresupuestal p = (PartidaPresupuestal) obj;
                partidaFiltro = p.toString();
            } else {
                partidaFiltro = null;
            };
            
            List<ReporteEntradas> listaIngresosFiltrada = new ArrayList<>();
            for (ReporteEntradas e : listaIngresos) {
                Date fechaDato = formato.parse(e.getFecha());
                boolean cumpleFecha = (fechaI == null || !fechaDato.before(fechaI)) && 
                                      (fechaF == null || !fechaDato.after(fechaF));
                boolean cumplePartida = (partidaFiltro == null || e.getPartidaPresupuestal().equals(partidaFiltro));

                if (cumpleFecha && cumplePartida) {
                    listaIngresosFiltrada.add(e);
                }
            }
            actualizarTablaIngresos(listaIngresosFiltrada);
            
            List<ReporteSalidas> listaEgresosFiltrada = new ArrayList<>();
            for (ReporteSalidas s : listaEgresos) {
                Date fechaDato = formato.parse(s.getFecha());
                boolean cumpleFecha = (fechaI == null || !fechaDato.before(fechaI)) && 
                                      (fechaF == null || !fechaDato.after(fechaF));
                boolean cumplePartida = (partidaFiltro == null || s.getPartidaPresupuestal().equals(partidaFiltro));
                if (cumpleFecha && cumplePartida) {
                    listaEgresosFiltrada.add(s);
                }
            }
            actualizarTablaEgresos(listaEgresosFiltrada);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Error: Formato de fecha incorrecto. Usa el formato aaaa-mm-dd");
        }
    }
    
    private String generarTitulo(String tipoReporte) {
        String partida = cbxPartidaPresupuestal.getSelectedIndex() > 0 
                         ? cbxPartidaPresupuestal.getSelectedItem().toString() : "";
        String inicio = txfFechaInicio.getText().trim();
        String fin = txfFechaFin.getText().trim();
        
        StringBuilder sb = new StringBuilder("Reporte de " + tipoReporte + " - ");
        sb.append(partida.isEmpty() ? "Todas las partidas" : "Partida: " + partida);
        sb.append("\n");

        if (inicio.isEmpty() && fin.isEmpty()) sb.append("Periodo: Todos los tiempos");
        else if (!inicio.isEmpty() && fin.isEmpty()) sb.append("Periodo: Desde el ").append(inicio);
        else if (inicio.isEmpty() && !fin.isEmpty()) sb.append("Periodo: Hasta el ").append(fin);
        else sb.append("Periodo: Desde el ").append(inicio).append(" hasta el ").append(fin);

        return sb.toString();
    }
    
    private void exportarPDF(DefaultTableModel modelo, String titulo, String nombreArchivo) {
        try {
            Document doc = new Document(PageSize.LETTER.rotate());
            PdfWriter.getInstance(doc, new FileOutputStream(nombreArchivo));
            doc.open();
            doc.add(new Paragraph(titulo));
            doc.add(new Paragraph(" "));
            PdfPTable table = new PdfPTable(modelo.getColumnCount());
            table.setWidthPercentage(100);
            for (int i = 0; i < modelo.getColumnCount(); i++) {
                table.addCell(modelo.getColumnName(i));
            }
            for (int i = 0; i < modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                    Object valor = modelo.getValueAt(i, j);
                    table.addCell(valor != null ? valor.toString() : "");
                }
            }
            doc.add(table);
            doc.close();
            JOptionPane.showMessageDialog(this, "PDF generado: " + nombreArchivo);
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(this, "El archivo o la ruta no existe", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (DocumentException e) {
            JOptionPane.showMessageDialog(this, "Error interno al generar el formato PDF, inténtelo más tarde", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnExportarPdfEgresos;
    private javax.swing.JButton btnExportarPdfIngresos;
    private javax.swing.JComboBox cbxPartidaPresupuestal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblEgresos;
    private javax.swing.JTable tblIngresos;
    private javax.swing.JFormattedTextField txfFechaFin;
    private javax.swing.JFormattedTextField txfFechaInicio;
    // End of variables declaration//GEN-END:variables
}
