/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectobd2.vista.vistassucursal.vistasalmacen;

import proyectobd2.modelo.DAO.AlertaStockMaximoDAO;

/**
 *
 * @author endri
 */
public class GUIItemsStockMaximo extends javax.swing.JPanel {

    AlertaStockMaximoDAO armDAO = new AlertaStockMaximoDAO();
    int idSucursal;
    /**
     * Creates new form GUIItemsStockMaximo
     */
    public GUIItemsStockMaximo(int idSucursal) {
        initComponents();
        this.idSucursal = idSucursal;
        armDAO.obtenerItemsStockMaximo(tb_stockMaximo, idSucursal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(50, 20), new java.awt.Dimension(25, 20), new java.awt.Dimension(50, 20));
        jLabel2 = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(150, 20), new java.awt.Dimension(100, 20), new java.awt.Dimension(150, 20));
        btn_exelMaximo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_stockMaximo = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        jPanel4.add(filler3);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Articulos con stock alto");
        jPanel4.add(jLabel2);
        jPanel4.add(filler2);

        btn_exelMaximo.setText("Exportar a excel");
        jPanel4.add(btn_exelMaximo);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        tb_stockMaximo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ARTICULO", "ATOCK ACTUAL", "STOCK MÁXIMO", "EXEDENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_stockMaximo);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exelMaximo;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_stockMaximo;
    // End of variables declaration//GEN-END:variables
}
